name: "Get MFA Secrets"
description: "Use Multi-Factor-Authentication (MFA) secrets in your GitHub Actions workflows"
inputs:
  secrets:
    description: "Secrets to fetch"
    required: true
  slack-webhook-url:
    description: "Webhook URL to send link to"
    required: false
branding:
  icon: "check-square"
  color: "green"
runs:
  using: "node16"
  main: "dist/index.js"
